### ISSUE TITLE
What happened with the service description metadata?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#246] opened 2019-07-21 06:18 UTC
Service discovery has been a common issue. Common approach is to provide some basic metadata about the service (title, abstracts, organization, keywords ...). We have this for the individual collection but I do not see any "path" to get or change this metadata.

Can we have a /info to describe the server a bit using ISO 19115 or Dublin core...

**Comment by cportele** [comment] 2019-07-21 06:57
I think, this is a duplicate of #160. 

In addition note that we had a discussion about adding more discovery metadata outside of the OpenAPI definition and we settled with adding title/description (#227), but ruled out anything more than that in the Core including tags (#228). You can always look at the API definition to get the contact info, etc.

That said, every API is free to add such information in the landing page or link to it from there. If it turns out that almost everyone would be adding certain information, it could be re-discussed whether more should be added.

**Comment by cmheazel** [comment] 2019-07-23 12:34
In addition, you are free to add additional elements to the OpenAPI description.  It's designed to be extended.

**Comment by joanma747** [comment] 2019-07-23 18:30
Apologies for duplicating the issue. I completely forgot that I submitted the in months ago.

"Being free to add" is not the same as "having an standard way to do it".

The Spatial Data on the Web Best Practices seems to care about this.

12.4 Spatial metadata
[DWBP] provides best practices discussing the provision of metadata to support discovery and reuse of data (see [DWBP] section 8.2 Metadata for more details). 
Best Practice 13: Include spatial metadata in dataset metadata
he description of datasets that have Spatial Things should include explicit metadata about their spatial extent, coverage, and representation

Best Practice 2: Provide descriptive metadata
Descriptive metadata can include the following overall features of a dataset:

The title and a description of the dataset.
The keywords describing the dataset.
The date of publication of the dataset.
The entity responsible (publisher) for making the dataset available.
The contact point for the dataset.
The spatial coverage of the dataset.
The temporal period that the dataset covers.
The date of last modification of the dataset.
The themes/categories covered by a dataset.
Descriptive metadata can include the following overall features of a distribution:

The title and a description of the distribution.
The date of publication of the distribution.
The media type of the distribution.

Currently we are about to release the first OGC API standard without a clear way to specify basic metadata. It is great that we have a "follow the links" approach that "google-like" crawlers can follow but, what are they going to find if there is no description of the dataset and their responsible parties...? If our "consumers" are the SDI there is something fundamentally wrong here. If our consumer is the IT mainstream, them, we are probably fine.

**Comment by cportele** [comment] 2019-07-29 16:43
We discussed this issue in a WFS SWG call and confirmed that https://github.com/opengeospatial/WFS_FES/issues/246#issuecomment-513528926 reflects the current position.

On the DWBP: Please note that the DWBP does not say "The following descriptive metadata should be included: ...", it says "descriptive metadata can include: ...". There is no recommendation that all of the elements are provided. That said, 

* an API is a distribution and title, description and media type(s) are supported; there is no guidance for "date of publication", but that's it;
* several of the descriptive metadata elements for a dataset are also supported - in the OpenAPI definition and/or in each collection.

I think the statement "if our 'consumers' are the SDI there is something fundamentally wrong here" is too harsh. It seems like we know different SDIs. Yes, many put a lot of emphasis on complex metadata specifications, but in general not much seems to depend on the manually captured metadata (for good reasons). But if an SDI requires, say, 19115-3 metadata for an API, then OGC API Features Core will not provide a standard solution for them. They will have to define their extensions (which seems straightforward to do) and convince implementers to support them.

Please also note the discussion and open issues with respect to dataset metadata in https://github.com/opengeospatial/WFS_FES/issues/102.

**Comment by cportele** [comment] 2019-08-12 14:05
SWG call 2019-08-12: The issue has been addressed. See the links to additional information.

**Closed by cportele** 2019-08-12 14:05 UTC
Labels: duplicate
